[project]
name = "daytona-mcp-interpreter"
version = "0.1.0"
description = "A Python code interpretation with claude running in Daytona Workstation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.3.0",
    "pydantic>=2.10.2",
    "python-dotenv>=1.0.1",
    "httpx>=0.24.0",
    "daytona-sdk>=0.9.1",
    "api-client>=1.3.1",
]

[project.scripts]
daytona-interpreter = "daytona_mcp_interpreter.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
